HAI
    I HAS A x ITZ 10
    I HAS A y ITZ 5

    VISIBLE BOTH SAEM x AN y
    VISIBLE DIFFRINT x AN y
    VISIBLE BIGGR OF x AN y
    VISIBLE SMALLR OF x AN y

    VISIBLE BOTH SAEM BIGGR OF x AN y AN x
    VISIBLE BOTH SAEM x AN BIGGR OF y AN x
KTHXBYE
