HAI
    WAZZUP 
        I HAS A x ITZ 10
        I HAS A y ITZ 5
    BUHBYE

    VISIBLE BOTH SAEM x AN y
    VISIBLE DIFFRINT x AN y
    VISIBLE BIGGR OF x AN y
    VISIBLE SMALLR OF x AN y

    VISIBLE BOTH SAEM x AN BIGGR OF x AN y
    VISIBLE BOTH SAEM x AN SMALLR OF x AN y
    VISIBLE DIFFRINT x AN SMALLR OF x AN y
    VISIBLE DIFFRINT x AN BIGGR OF x AN y
KTHXBYE
